In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [55]:
%tensorflow_version 2.x

In [56]:
import os 
os.listdir('/content/drive/My Drive/Text generation')

['moby_dick_four_chapters.txt']

In [57]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [58]:
tf.__version__



'2.2.0'

In [59]:
path= '/content/drive/My Drive/Text generation/moby_dick_four_chapters.txt'
text = open(path, 'r').read()

In [60]:
print(text[:500])

Call me Ishmael.  Some years ago--never mind how long
precisely--having little or no money in my purse, and nothing
particular to interest me on shore, I thought I would sail about a
little and see the watery part of the world.  It is a way I have of
driving off the spleen and regulating the circulation.  Whenever I
find myself growing grim about the mouth; whenever it is a damp,
drizzly November in my soul; whenever I find myself involuntarily
pausing before coffin warehouses, and bringing up t


In [61]:
vocab = sorted(set(text))
print(vocab)
len(vocab)

['\n', ' ', '!', '"', "'", '(', ')', ',', '-', '.', '1', '2', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


66

In [62]:
char_to_ind = {u:i for i, u in enumerate(vocab)}

In [63]:
char_to_ind

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 "'": 4,
 '(': 5,
 ')': 6,
 ',': 7,
 '-': 8,
 '.': 9,
 '1': 10,
 '2': 11,
 ':': 12,
 ';': 13,
 '?': 14,
 'A': 15,
 'B': 16,
 'C': 17,
 'D': 18,
 'E': 19,
 'F': 20,
 'G': 21,
 'H': 22,
 'I': 23,
 'J': 24,
 'K': 25,
 'L': 26,
 'M': 27,
 'N': 28,
 'O': 29,
 'P': 30,
 'Q': 31,
 'R': 32,
 'S': 33,
 'T': 34,
 'U': 35,
 'V': 36,
 'W': 37,
 'Y': 38,
 'Z': 39,
 'a': 40,
 'b': 41,
 'c': 42,
 'd': 43,
 'e': 44,
 'f': 45,
 'g': 46,
 'h': 47,
 'i': 48,
 'j': 49,
 'k': 50,
 'l': 51,
 'm': 52,
 'n': 53,
 'o': 54,
 'p': 55,
 'q': 56,
 'r': 57,
 's': 58,
 't': 59,
 'u': 60,
 'v': 61,
 'w': 62,
 'x': 63,
 'y': 64,
 'z': 65}

In [64]:
ind_to_char = np.array(vocab)

In [65]:
ind_to_char

array(['\n', ' ', '!', '"', "'", '(', ')', ',', '-', '.', '1', '2', ':',
       ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K',
       'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'Y',
       'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l',
       'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y',
       'z'], dtype='<U1')

In [66]:
vocab

['\n',
 ' ',
 '!',
 '"',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '1',
 '2',
 ':',
 ';',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'Y',
 'Z',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [67]:
encoded_text = np.array([char_to_ind[c] for c in text])

In [68]:
encoded_text

array([17, 40, 51, ..., 54, 53,  9])

In [69]:
sample = text[:20]
sample

'Call me Ishmael.  So'

In [70]:
encoded_text[:20]

array([17, 40, 51, 51,  1, 52, 44,  1, 23, 58, 47, 52, 40, 44, 51,  9,  1,
        1, 33, 54])

In [71]:
print(text[:500])

Call me Ishmael.  Some years ago--never mind how long
precisely--having little or no money in my purse, and nothing
particular to interest me on shore, I thought I would sail about a
little and see the watery part of the world.  It is a way I have of
driving off the spleen and regulating the circulation.  Whenever I
find myself growing grim about the mouth; whenever it is a damp,
drizzly November in my soul; whenever I find myself involuntarily
pausing before coffin warehouses, and bringing up t


In [72]:
seq_len = 120

In [73]:
total_num_seq = len(text)//(seq_len+1)

In [74]:
total_num_seq

509

In [75]:
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)

# for i in char_dataset.take(500):
#      print(ind_to_char[i.numpy()])

In [76]:
sequences = char_dataset.batch(seq_len+1, drop_remainder=True)

In [77]:
def create_seq_targets(seq):
    input_txt = seq[:-1]
    target_txt = seq[1:]
    return input_txt, target_txt

In [78]:
dataset = sequences.map(create_seq_targets)

In [79]:
for input_txt, target_txt in  dataset.take(1):
    print(input_txt.numpy())
    print(''.join(ind_to_char[input_txt.numpy()]))
    print('\n')
    print(target_txt.numpy())
    # There is an extra whitespace!
    print(''.join(ind_to_char[target_txt.numpy()]))

[17 40 51 51  1 52 44  1 23 58 47 52 40 44 51  9  1  1 33 54 52 44  1 64
 44 40 57 58  1 40 46 54  8  8 53 44 61 44 57  1 52 48 53 43  1 47 54 62
  1 51 54 53 46  0 55 57 44 42 48 58 44 51 64  8  8 47 40 61 48 53 46  1
 51 48 59 59 51 44  1 54 57  1 53 54  1 52 54 53 44 64  1 48 53  1 52 64
  1 55 60 57 58 44  7  1 40 53 43  1 53 54 59 47 48 53 46  0 55 40 57 59]
Call me Ishmael.  Some years ago--never mind how long
precisely--having little or no money in my purse, and nothing
part


[40 51 51  1 52 44  1 23 58 47 52 40 44 51  9  1  1 33 54 52 44  1 64 44
 40 57 58  1 40 46 54  8  8 53 44 61 44 57  1 52 48 53 43  1 47 54 62  1
 51 54 53 46  0 55 57 44 42 48 58 44 51 64  8  8 47 40 61 48 53 46  1 51
 48 59 59 51 44  1 54 57  1 53 54  1 52 54 53 44 64  1 48 53  1 52 64  1
 55 60 57 58 44  7  1 40 53 43  1 53 54 59 47 48 53 46  0 55 40 57 59 48]
all me Ishmael.  Some years ago--never mind how long
precisely--having little or no money in my purse, and nothing
parti


In [80]:
# Batch size
batch_size = 128

# Buffer size to shuffle the dataset so it doesn't attempt to shuffle
# the entire sequence in memory. Instead, it maintains a buffer in which it shuffles elements
buffer_size = 10000

dataset = dataset.shuffle(buffer_size).batch(batch_size, drop_remainder=True)

In [81]:
dataset

<BatchDataset shapes: ((128, 120), (128, 120)), types: (tf.int64, tf.int64)>

In [116]:
# Length of the vocabulary in chars
vocab_size = len(vocab)

# The embedding dimension
embed_dim = 64

# Number of RNN units
rnn_neurons = 1026

In [117]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense,Embedding,Dropout,GRU

In [118]:
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [85]:
help(sparse_categorical_crossentropy)

Help on function sparse_categorical_crossentropy in module tensorflow.python.keras.losses:

sparse_categorical_crossentropy(y_true, y_pred, from_logits=False, axis=-1)
    Computes the sparse categorical crossentropy loss.
    
    Usage:
    
    >>> y_true = [1, 2]
    >>> y_pred = [[0.05, 0.95, 0], [0.1, 0.8, 0.1]]
    >>> loss = tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred)
    >>> assert loss.shape == (2,)
    >>> loss.numpy()
    array([0.0513, 2.303], dtype=float32)
    
    Args:
      y_true: Ground truth values.
      y_pred: The predicted values.
      from_logits: Whether `y_pred` is expected to be a logits tensor. By default,
        we assume that `y_pred` encodes a probability distribution.
      axis: (Optional) Defaults to -1. The dimension along which the entropy is
        computed.
    
    Returns:
      Sparse categorical crossentropy loss value.



In [86]:
def sparse_cat_loss(y_true,y_pred):
  return sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)

In [119]:
def create_model(vocab_size, embed_dim, rnn_neurons, batch_size):
    model = Sequential()
    model.add(Embedding(vocab_size, embed_dim,batch_input_shape=[batch_size, None]))
    model.add(GRU(rnn_neurons,return_sequences=True,stateful=True,recurrent_initializer='glorot_uniform'))
    # Final Dense Layer to Predict
    model.add(Dense(vocab_size))
    model.compile(optimizer='adam', loss=sparse_cat_loss) 
    return model

In [103]:
model = create_model(
  vocab_size = vocab_size,
  embed_dim=embed_dim,
  rnn_neurons=rnn_neurons,
  batch_size=batch_size)

In [104]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_6 (Embedding)      (128, None, 64)           4224      
_________________________________________________________________
gru_6 (GRU)                  (128, None, 1026)         3361176   
_________________________________________________________________
dense_6 (Dense)              (128, None, 66)           67782     
Total params: 3,433,182
Trainable params: 3,433,182
Non-trainable params: 0
_________________________________________________________________


In [105]:
for input_example_batch, target_example_batch in dataset.take(1):

  # Predict off some random batch
  example_batch_predictions = model(input_example_batch)

  # Display the dimensions of the predictions
  print(example_batch_predictions.shape, " <=== (batch_size, sequence_length, vocab_size)")


(128, 120, 66)  <=== (batch_size, sequence_length, vocab_size)


In [106]:
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)

In [107]:
epochs = 300

In [108]:
model.fit(dataset,epochs=epochs)

Epoch 1/300
3/3 [==============================] - 1s 168ms/step - loss: 4.1598
Epoch 2/300
3/3 [==============================] - 0s 155ms/step - loss: 4.8808
Epoch 3/300
3/3 [==============================] - 0s 151ms/step - loss: 3.9548
Epoch 4/300
3/3 [==============================] - 0s 147ms/step - loss: 3.9417
Epoch 5/300
3/3 [==============================] - 0s 145ms/step - loss: 3.7519
Epoch 6/300
3/3 [==============================] - 0s 146ms/step - loss: 3.6372
Epoch 7/300
3/3 [==============================] - 0s 144ms/step - loss: 3.5018
Epoch 8/300
3/3 [==============================] - 0s 150ms/step - loss: 3.3386
Epoch 9/300
3/3 [==============================] - 0s 147ms/step - loss: 3.1896
Epoch 10/300
3/3 [==============================] - 0s 144ms/step - loss: 3.0941
Epoch 11/300
3/3 [==============================] - 0s 145ms/step - loss: 3.1044
Epoch 12/300
3/3 [==============================] - 0s 147ms/step - loss: 3.0814
Epoch 13/300
3/3 [===================

In [109]:
model.save('moby.h5') 

In [110]:
from tensorflow.keras.models import load_model

In [111]:
model = create_model(vocab_size, embed_dim, rnn_neurons, batch_size=1)

model.load_weights('moby.h5')

model.build(tf.TensorShape([1, None]))


In [112]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_7 (Embedding)      (1, None, 64)             4224      
_________________________________________________________________
gru_7 (GRU)                  (1, None, 1026)           3361176   
_________________________________________________________________
dense_7 (Dense)              (1, None, 66)             67782     
Total params: 3,433,182
Trainable params: 3,433,182
Non-trainable params: 0
_________________________________________________________________


In [113]:
def generate_text(model, start_seed,gen_size=100,temp=1.0):
  '''
  model: Trained Model to Generate Text
  start_seed: Intial Seed text in string form
  gen_size: Number of characters to generate

  Basic idea behind this function is to take in some seed text, format it so
  that it is in the correct shape for our network, then loop the sequence as
  we keep adding our own predicted characters. Similar to our work in the RNN
  time series problems.
  '''

  # Number of characters to generate
  num_generate = gen_size

  # Vecotrizing starting seed text
  input_eval = [char_to_ind[s] for s in start_seed]

  # Expand to match batch format shape
  input_eval = tf.expand_dims(input_eval, 0)

  # Empty list to hold resulting generated text
  text_generated = []

  # Temperature effects randomness in our resulting text
  # The term is derived from entropy/thermodynamics.
  # The temperature is used to effect probability of next characters.
  # Higher probability == lesss surprising/ more expected
  # Lower temperature == more surprising / less expected
 
  temperature = temp

  # Here batch size == 1
  model.reset_states()

  for i in range(num_generate):

      # Generate Predictions
      predictions = model(input_eval)

      # Remove the batch shape dimension
      predictions = tf.squeeze(predictions, 0)

      # Use a cateogircal disitribution to select the next character
      predictions = predictions / temperature
      predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()

      # Pass the predicted charracter for the next input
      input_eval = tf.expand_dims([predicted_id], 0)

      # Transform back to character letter
      text_generated.append(ind_to_char[predicted_id])

  return (start_seed + ''.join(text_generated))

In [114]:

print(generate_text(model,"The",gen_size=1000))

The Offite may in.

Brad chose
world's with the hair
on.  Place meselvide of the leggom in the sounds of the tinkly pleas.  But these warlay canclight
to be hight; the counterpane, I arm thrown ovey my blooken's sates--night semething his a meanard
ly.  I concluded that this harpooneer, in the course very lare, and he id to curere syent, but stop; could 't all remembering what the
landlord said about the Gar semmer wes with
leggo pactious condlinded jorty tceay reador you could and came
near boor was new
betan from thens," but I began to feel ous bettlep, I fectullous do tow in the air which smourd
in the wird
clene to a dime jistincuin begous.  Besides, I ain't insured."

This being told to Queequeg, he at once complied, and again the strangest
possible manners.  His education was not yet completed.  He was an
upper oun on the coanser deef quiets and jolly there.  Fere was no tomowh, frim that I am in the habit of going to see hours you and sheper drowned.  But that some of monning th